name: cypress tests
on: [push]
jobs:
  cypress-smoke-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: setup npm package
        run: npm install         
      - name: run test scripts
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npx cypress run --spec cypress//integration//features//ui//fleet-admin//signup-scenarios.feature
      - name: generate the results
        run: node .//cypress//htmlreport.js
