name: cypress tests
on: [push]
jobs:
  cypress-smoke-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run cypress:smoke:headless
        
    
     
